libraries:                       # This is called out once within the config.yml file
  Movies:                        # These are names of libraries in your Plex
    metadata_path:
    - folder: config/Movies
  TV Shows:
    metadata_path:
    - folder: config/TVShows
#   Music:
#     metadata_path:
#     - file: config/Music.yml     # This is a local file THAT YOU MIGHT CREATE
playlist_files:
  - folder: config/Playlists                  # This is a file within PMM's defaults folder
  #see the wiki for how to use local files, folders, URLs, or files from git
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  - tmdb_show: 278
  - tmdb_show: 60694
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: true
webhooks:                        # Can be individually specified per library as well
  error: notifiarr
  version:
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://localhost:32400
  token: [redacted]
  timeout: 1200
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache:
tmdb:                            # REQUIRED for the script to run
  apikey: [redacted]
  language: en
  cache_expiration: 60
  region:
tautulli:                        # Can be individually specified per library as well
  url: http://localhost:8181
  apikey: [redacted]
omdb:
  apikey: [redacted]
  cache_expiration: 60
mdblist:
  apikey: [redacted]
  cache_expiration: 60
notifiarr:
  apikey: [redacted]
radarr:                          # Can be individually specified per library as well
  url: http://localhost:7878
  token: [redacted]
  add_missing: true
  add_existing: false
  root_folder_path: path
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
sonarr:                          # Can be individually specified per library as well
  url: http://localhost:8989
  token: [redacted]
  add_missing: false
  add_existing: false
  root_folder_path: path
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false
trakt:
  client_id: [redacted]
  client_secret: [redacted]
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: 
    token_type: 
    expires_in: 
    refresh_token: 
    scope: 
    created_at: 
