libraries:
  Movies:
    template_variables:
      use_separator: false  
    metadata_path:
    - folder: config/Movies
    - git: PMM/award/bafta
      template_variables:
        data:
          starting: current_year-5
          ending: current_year
    - git: PMM/award/cannes
    - git: PMM/award/choice
      template_variables:
        data:
          starting: current_year-5
          ending: current_year
    - git: PMM/award/golden
    - git: PMM/award/oscars
      template_variables:
        data:
          starting: current_year-5
          ending: current_year
    - git: PMM/award/other
    - git: PMM/award/spirit
    - git: PMM/award/sundance
    - git: PMM/chart/basic
    - git: PMM/chart/imdb
#    - git: PMM/chart/other
#    - git: PMM/chart/tautulli
    - git: PMM/chart/tmdb
#    - git: PMM/chart/trakt
#    - git: PMM/actor
    - git: PMM/audio_language
      template_variables:
        include: 
            - en
            - fr
            - de
            - es
        use_other: false
        sort_by: year.asc
#    - git: PMM/movie/content_rating_us           # Choose content_rating_uk or content_rating_us
#    - git: PMM/genre
#    - git: PMM/resolution_standards              # Choose resolution_standards or resolution
    - git: PMM/streaming
    - git: PMM/studio
#    - git: PMM/subtitle_language
    - git: PMM/year
      template_variables:
        data:
          starting: current_year-2
          ending: current_year
    - git: PMM/movie/country
      template_variables:
        style: color
        include:
            - Australia
            - Canada
            - France
            - Germany
            - Ireland
            - New Zealand
            - Spain
            - United Kingdom
            - United States of America
        use_other: false
        sort_by: year.asc
#    - git: PMM/movie/decade
#    - git: PMM/movie/director
#    - git: PMM/movie/franchise
#      template_variables:
#        minimum_items: 3
#        sort_title: "!15_<<collection_name>>"
#    - git: PMM/movie/universe
#      template_variables:
#        use_separator: false
#    - git: PMM/movie/producer
#    - git: PMM/movie/seasonal
#    - git: PMM/movie/writer
#    overlay_path:
#    - remove_overlays: true
#    - git: PMM/overlays/imdb_top_250
#    - git: PMM/overlays/ratings
#    - git: PMM/overlays/resolution
#    - git: PMM/overlays/special_release
  TV Shows:
    template_variables:
      use_separator: false  
    metadata_path:
    - folder: config/TVShows
    - git: PMM/award/choice 
      template_variables:
        radarr_add_missing: false
    - git: PMM/award/golden
      template_variables:
        radarr_add_missing: false
    - git: PMM/award/emmy
      template_variables:
        radarr_add_missing: false
#    - git: PMM/chart/anilist
    - git: PMM/chart/basic
    - git: PMM/chart/imdb
      template_variables:
        radarr_add_missing: false
    - git: PMM/chart/other
      template_variables:
        radarr_add_missing: false
#    - git: PMM/chart/tautulli
    - git: PMM/chart/tmdb
#    - git: PMM/chart/trakt
#    - git: PMM/actor
    - git: PMM/audio_language
      template_variables:
        include: 
          - en
          - fr
          - de
          - es
        use_other: false
        sort_by: year.asc
#    - git: PMM/show/content_rating_us            # Choose content_rating_uk or content_rating_us
#    - git: PMM/genre
#    - git: PMM/resolution_standards              # Choose resolution_standards or resolution
    - git: PMM/streaming
    - git: PMM/studio
#    - git: PMM/subtitle_language
    - git: PMM/year
      template_variables:
        data:
          starting: current_year-2
          ending: current_year
    - git: PMM/show/country
      template_variables:
        style: color
        use_other: false
        sort_by: year.asc
    - git: PMM/show/decade
    - git: PMM/show/network
      template_variables:
        include: 
          - A&E
          - ABC
          - Adult Swim
          - Amazon
          - AMC
          - Animal Planet
          - BBC
          - BET
          - Bravo
          - Cartoon Network
          - Channel 4
          - Channel 5
          - CBC
          - CBBC
          - CBS
          - Comedy Central
          - Discovery
          - Disney Channel
          - E!
          - Epix
          - ESPN
          - FX
          - Food Network
          - FOX
          - Hallmark
          - HBO
          - HGTV
          - History
          - ITV
          - Lifetime
          - MTV
          - National Geographic
          - NBC
          - Nickelodeon
          - PBS
          - Sky
          - Showtime
          - Spike
          - Starz
          - SundanceTV
          - Syfy
          - TBS
          - The CW
          - TLC
          - TNT
          - TV Land
          - UKTV
          - UPN
          - USA
          - VH1
          - The WB
          - YouTube
        use_other: false
        sort_by: year.asc
#    overlay_path:
#    - remove_overlays: true
#    - git: PMM/overlays/ratings
#    - git: PMM/overlays/ratings
#      template_variables:
#        overlay_level: episode
#    - git: PMM/overlays/ratings
#      template_variables:
#        overlay_level: season
#    - file: config/TVShows.yml
playlist_files:
- git: PMM/playlist
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
webhooks:                                       # Can be individually specified per library as well
  error: notifiarr
  version:
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://localhost:32400
  token: correcttokenhere
  timeout: 1200
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: correctapihere
  language: en
  cache_expiration: 60
  region:
tautulli:                                       # Can be individually specified per library as well
  url: http://localhost:8181
  apikey: correctapihere
omdb:
  apikey: correctapihere
  cache_expiration: 60
mdblist:
  apikey: correctapirehere
  cache_expiration: 60
notifiarr:
  apikey: correctapihere
radarr:                                         # Can be individually specified per library as well
  url: http://localhost:7878
  token: correctokenhere
  add_missing: true
  add_existing: false
  root_folder_path: correctpathhere
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag:
  search: true
  radarr_path:
  plex_path:
  upgrade_existing: false
sonarr:                                         # Can be individually specified per library as well
  url: http://localhost:8989
  token: correcttokenhere
  add_missing: false
  add_existing: false
  root_folder_path: correctpathhere
  monitor: all
  quality_profile: any
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: true
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
trakt:
  client_id: correctidhere
  client_secret: correctsecrethere
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: 
    token_type: 
    expires_in: 
    refresh_token: 
    scope: 
    created_at: 
